version: "3"
services:
  user-fpm:
    image : manaphp/php74:210801
    volumes:
      - ../:/var/www/html
      - ./fpm/etc/fpm.conf:/etc/php/fpm.conf
      - ./fpm/etc/php.ini:/etc/php/php.ini
      - /data/volumes/${COMPOSE_PROJECT_NAME}/user/fpm:/var/log/php
      - /data/volumes/${COMPOSE_PROJECT_NAME}/user/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/user/tmp:/var/www/html/tmp
    command : bash /var/www/html/docker/fpm/bootstrap.sh
    restart: always
  user-nginx:
    image: nginx:1.19.6
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ../:/var/www/html
      - .nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/volumes/${COMPOSE_PROJECT_NAME}/user/nginx:/var/log/nginx
    ports:
      - ${WEB_PORT}:80
    restart: always
