version: "2"
services:
  user_fpm:
    image: manaphp/php73:2.0
    volumes: 
      - ../:/var/www/html
      - ./fpm/conf.d:/etc/php/conf.d
      - /data/volumes/${COMPOSE_PROJECT_NAME}/user/fpm:/var/log/php
      - /data/volumes/${COMPOSE_PROJECT_NAME}/user/app/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/user/app/tmp:/var/www/html/tmp
    restart: always
  user_nginx:
    image: nginx:1.13.3
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ../:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/volumes/${COMPOSE_PROJECT_NAME}/user/nginx:/var/log/nginx
    ports:
      - ${WEB_PORT}:80
    restart: always
